bddl_files_path: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/bddl_files"
script_path: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/notebooks/generate_init_states.py"
init_file_dir: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero/libero/init_files/"

use_environment: true
use_swap: false
use_object: false
use_language: false
use_task: false

ood_task_configs:
  environment: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero_ood/ood_environment.yaml"
  swap: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero_ood/ood_spatial_relation.yaml"
  object: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero_ood/ood_object.yaml"
  language: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero_ood/ood_language.yaml"
  task: "/hdd/zijianwang/openpi/third_party/LIBERO-PRO/libero_ood/ood_task.yaml"
